from upload_depends.upload import upload_image, delete_uploaded_image
from upload_depends.upload_lesson import upload_lesson, delete_uploaded_lesson 
from upload_depends.upload_portfolio import upload_portfolio, delete_uploaded_portfolio 